// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace TimeLapse.POCO
{
    // Scores
    public partial class Score
    {
        public Guid ScoreId { get; set; } // ScoreID (Primary key)
        public int Ranking { get; set; } // Ranking
        public Guid PointId { get; set; } // PointID
        public Guid SeasonId { get; set; } // SeasonID
        public Guid ChampionshipId { get; set; } // ChampionshipID

        // Foreign keys
        public virtual Championship Championship { get; set; } // FK__Scores__Champion__4AB81AF0
        public virtual Point Point { get; set; } // FK__Scores__PointID__48CFD27E
        public virtual Season Season { get; set; } // FK__Scores__SeasonID__49C3F6B7
        
        public Score()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
